version: '3.8'

services:
  api:
    build:
      context: ./wallet-api
      target: build
    volumes:
      - type: bind
        source: ./wallet-api/src
        target: /app/src
        consistency: delegated
    environment:
      - TSC_WATCHFILE=UseFsEvents

  processor:
    build:
      context: ./wallet-processor
      target: build
    volumes:
      - type: bind
        source: ./wallet-processor/src
        target: /app/src
        consistency: delegated
    environment:
      - TSC_WATCHFILE=UseFsEvents
